name: Debug Secrets

on:
  workflow_dispatch:  # Manual trigger only for security
  # Don't run on push/PR to avoid exposing secrets in logs

jobs:
  debug-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Method 1: Check if secret exists (recommended)
    - name: Check if Docker username secret exists
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "❌ DOCKER_USERNAME secret is empty or not set"
        else
          echo "✅ DOCKER_USERNAME secret is set"
          echo "Length: ${#DOCKER_USERNAME}"
        fi
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    - name: Check if Docker token secret exists
      run: |
        if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
          echo "❌ DOCKERHUB_TOKEN secret is empty or not set"
        else
          echo "✅ DOCKERHUB_TOKEN secret is set"
          echo "Length: ${#DOCKERHUB_TOKEN}"
        fi
      env:
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    # Method 2: Show first/last few characters (safer partial reveal)
    - name: Show partial secret values
      run: |
        echo "DOCKER_USERNAME first 3 chars: ${DOCKER_USERNAME:0:3}***"
        echo "DOCKERHUB_TOKEN first 4 chars: ${DOCKERHUB_TOKEN:0:4}***"
        echo "DOCKERHUB_TOKEN last 4 chars: ***${DOCKERHUB_TOKEN: -4}"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    # # Method 3: ONLY FOR TEMPORARY DEBUGGING - prints full secret
    # # ⚠️  DELETE THIS STEP AFTER DEBUGGING ⚠️
    # - name: Print full secrets (REMOVE AFTER DEBUGGING)
    #   run: |
    #     echo "Full DOCKER_USERNAME: $DOCKER_USERNAME"
    #     echo "Full DOCKERHUB_TOKEN: $DOCKERHUB_TOKEN"
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    # Method 4: Test Docker login with the secrets
    - name: Test Docker login
      run: |
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
        echo "✅ Docker login successful"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}